MyCourseWork/MyCourseWork/Controllers/AdminController.cs
using BLLAbstractions.Interfaces;
using Core.DbModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyCourseWork.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCourseWork.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IGenericService<User> _genericService;

        private readonly IGenericService<Role> _rolesService;


        public AdminController(IGenericService<User> genericService,
            IGenericService<Role> rolesService)
        {
            _genericService = genericService;
            _rolesService = rolesService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> Details(int id)
        {
            return await GetUserFields(id);
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["RolesList"] = new SelectList(await _rolesService.GetAll(), "Id", "Name");
            return await GetUserFields(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(User newUser)
        {
            await _genericService.Update(newUser);
            return RedirectToAction("GetAll");

        }

        public async Task<IActionResult> Delete(int id)
        {
            return  await GetUserFields(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(User user)
        {
            await _genericService.Remove(user);
            return RedirectToAction("GetAll");

        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var readResult = await _genericService.GetAll();
            return View(readResult);
        }

        [HttpGet]
        private async Task<IActionResult> GetUserFields(int id)
        {
            var serviceResult = await _genericService.GetById(id);
            return View(serviceResult);
        }
    }
}

MyCourseWork/MyCourseWork/Controllers/CartController.cs
using System.Linq;
using System.Threading.Tasks;
using Core.DbModels;
using DALAbstractions.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MyCourseWork.Models;
using MyCourseWork.Models.CartModels;

namespace MyCourseWork.Controllers
{
    public class CartController : Controller
    {
        private readonly IGenericRepository<Product> _repository;
        
        private readonly IGenericRepository<CartItem> _cartItemRepository;
        
        private readonly Cart _cart;

        public CartController(IGenericRepository<Product> repository, Cart cart, IGenericRepository<CartItem> cartItemRepository)
        {
            _repository = repository;
            _cart = cart;
            _cartItemRepository = cartItemRepository;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var items = await _cartItemRepository.GetWhere(x => x.CartProductId == _cart.CartId);
            var product = await _repository.GetAll();
            _cart.CartItems = items.ToList();

            if (_cart.CartItems.Count == 0)
            {
                ModelState.AddModelError("", "Корзина пуста");
                ViewBag.Message = "Корзина пуста";
                return View();
            }

            var obj = new CartViewModel()
            {
                Cart = _cart
            };

            return View(obj);
        }

        [Authorize]
        public RedirectToActionResult AddToCart(int id)
        {
            var item = _repository.GetAll().Result.FirstOrDefault(x => x.Id == id);
            if (item != null)
            {
                _cart.AddToCart(item, _cart);
            }

            return RedirectToAction(nameof(Index), "Product");
        }
        
        [Authorize]
        public RedirectToActionResult RemoveFromCart(int id)
        {
            var item = _repository.GetAll().Result.FirstOrDefault(x => x.Id == id);
            if (item != null)
            {
                _cart.DeleteFromCart(id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

MyCourseWork/MyCourseWork/Controllers/PlaceController.cs
using BLLAbstractions.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCourseWork.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Core.DbModels;

namespace MyCourseWork.Controllers
{
    public class PlaceController : Controller
    {
        private readonly IGenericService<Place> _genericService;

        public PlaceController(IGenericService<Place> genericService)
        {
            _genericService = genericService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(Place place)
        {
            await _genericService.Add(place);
            return Redirect("GetAll");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            return await GetUserFields(id);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            return await GetUserFields(id);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Place newPlace)
        {
            await _genericService.Update(newPlace);
            return RedirectToAction("GetAll");

        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            return await GetUserFields(id);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Place place)
        {
            await _genericService.Remove(place);
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetAll()
        {
            var readResult = await _genericService.GetAll();
            return View(readResult);
        }

        [Authorize]
        public async Task<IActionResult> Sort(string searchString)
        {
            var places = await _genericService.GetAll();
            
            if (!String.IsNullOrEmpty(searchString.ToLower()))
            {
                places = places
                    .Where(s => s.Name.ToLower().Contains(searchString.ToLower()) 
                || s.OwnerShipType.ToLower().Contains(searchString.ToLower()) 
                || s.Phones.ToLower().Contains(searchString.ToLower()) 
                || s.Specialisation.ToLower().Contains(searchString.ToLower())
                || s.WorkTime.ToLower().Contains(searchString.ToLower()));
                
            }

            return View(places);
        }

        [HttpGet]
        [Authorize]
        private async Task<IActionResult> GetUserFields(int id)
        {
            var result = await _genericService.GetById(id);
            return View(result);
        }
    }
}

MyCourseWork/MyCourseWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCourseWork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav  class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link ml-2  text-light" asp-area="" asp-controller="Place" asp-action="GetAll">Магазины</a>
                        
                    @if (User.IsInRole("admin"))
                    {
                        <a class="nav-link  ml-2  text-light" asp-area="" asp-controller="Admin" asp-action="GetAll">Список аккаунтов</a>
                    }
                        <a class="nav-link  ml-2  text-light" asp-area="" asp-controller="Product" asp-action="Index">Список товаров</a>
                        
                        <a class="nav-link  ml-2  text-light" asp-area="" asp-controller="Cart" asp-action="Index">Корзина</a>
                        
                        <a class="btn btn-primary  text-light" asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyCourseWork - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>